[package]
name = "generate_state_changes"
version = "0.1.0"
authors = ["Christian Duerr <contact@christianduerr.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.2"
